### ISSUE TITLE
Missing configure executable

### ISSUE THREAD

**Issue by xxyxxyxyx1** [outpaddling/makedepf90#1]
Hello,

Perhaps I am missing something obvious, but I was unable to follow the compilation instructions in the readme. 

When I try `./configure`, I receive `No such file or directory`. I see there is a file named "configure.in," but I can't execute that either. 

What am I doing wrong?

**Comment by outpaddling** [comment]
Just run "make" (or "gmake" if you're on a system that does not use GNU make by default).
I'm not sure about the instructions.  I didn't write this tool, but just recently rescued it from oblivion.
