### ISSUE TITLE
Info request about project

### ISSUE THREAD

**Issue by artu72** [outpaddling/makedepf90#3]
Dear Jason,
I wonder that your project is no longer mantained. I use makedepf90 in my fortran projects and it is a very useful tool. I work on Fedora linux distro, and I have found that the package makedepf90 is no longer mantained due to dead upstream. 
 Looking for your reply, my best regards.
Andrea

**Comment by outpaddling** [comment]
Hello Andrea,
makedepf90 is not my project, actually.  I posted a copy of the source here because I could not find a site where it could be automatically downloaded by package managers.  Sorry I cannot offer more assistance.
Regards,
    Jason
