### ISSUE TITLE
PREFIX path bugged because of "destdir" support

### ISSUE THREAD

**Issue by adnan-umich** [outpaddling/makedepf90#5]
Hello, since you've added/modified the install and install-strip in the Makefile.in 

install: $(PROG)  makedepf90.1
	$(INSTALL) -d $(**DESTDIR**)$(bindir)
	$(INSTALL_PROGRAM) $(PROG) $(DESTDIR)$(bindir)
	$(INSTALL) -d $(DESTDIR)$(mandir)/man1
	$(INSTALL_DATA) makedepf90.1 $(DESTDIR)$(mandir)/man1
install-strip: $(PROG) makedepf90.1
	$(INSTALL) -d $(DESTDIR)$(bindir)
	$(INSTALL_PROGRAM) -s $(PROG) $(DESTDIR)$(bindir)
	$(INSTALL) -d $(DESTDIR)$(mandir)/man1
	$(INSTALL_DATA) makedepf90.1 $(DESTDIR)$(mandir)/man1

I think what you intended with this was to allow users to select an alternative install directory. But the proper way is to first run "autoconf" which generates a configure script from the configure.in file. The user can then do

./configure --prefix=/install/path/
make
make install

This is the intended way. Although perhaps you thought differently, so I am open to your perspective on why you think commits e40c9ca, a704404, bf704d7 are important and required?

**Comment by outpaddling** [comment]
No, destdir is separate from the install prefix.  It's purpose is to support staged installs, which allows package managers to check for conflicts, ensure proper permissions, etc.  DESTDIR is empty by default and inserted by build systems that stage the install in a temporary directory.

[https://www.gnu.org/prep/standards/html_node/DESTDIR.html](https://www.gnu.org/prep/standards/html_node/DESTDIR.html)

**Comment by adnan-umich** [comment]
That makes a lot of sense, I forgot about **make DESTDIR=/tmp/stage install**

Thank you kind sir. 

A
